language: python

python:
  - "3.6"

sudo: required

dist: trusty

services:
  - docker

addons:
  apt:
    packages:
      - python3-gdal

install:
  - docker build -t app .
  - docker run -d --name app app

before_script:
  - pip install -r requirements.txt

script:
  - docker ps | grep -q app
  - python manage.py test
