version: '2'
services:
  db:
    image: postgres
    container_name: escrutinio-social-db
    environment:
      - POSTGRES_DB=escrutiniociudadano
      - POSTGRES_USER=escrutinio
      - POSTGRES_PASSWORD=development
  web:
    container_name: escrutinio-social-web
    build: .
    volumes:
      - ./:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
