# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionVoluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='elecciones.Mesa')),
            ],
            options={
                'verbose_name': 'Asignación de voluntari@',
                'verbose_name_plural': 'Asignación de voluntari@s',
            },
        ),
        migrations.CreateModel(
            name='DatoDeContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('teléfono', 'teléfono'), ('email', 'email'), ('web', 'web'), ('twitter', 'twitter'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('skype', 'skype')], max_length=20)),
                ('valor', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', model_utils.fields.StatusField(choices=[('PRE-INSCRIPTO', 'PRE-INSCRIPTO'), ('CONFIRMADO', 'CONFIRMADO'), ('DECLINADO', 'DECLINADO')], default='PRE-INSCRIPTO', max_length=100, no_check_for_status=True)),
                ('codigo_confirmacion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email_confirmado', models.BooleanField(default=False)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_dni', models.CharField(choices=[('DNI', 'DNI'), ('CI', 'CI'), ('LE', 'LE'), ('LC', 'LC')], default='DNI', max_length=3)),
                ('dni', models.CharField(blank=True, max_length=15, null=True)),
                ('escuela_donde_vota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.LugarVotacion')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Voluntari@s',
            },
        ),
        migrations.CreateModel(
            name='VotoMesaOficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.PositiveIntegerField(null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Mesa')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Opcion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VotoMesaReportado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.PositiveIntegerField(null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Mesa')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Opcion')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscales.Voluntario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asignacionvoluntario',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_mesa', to='fiscales.Voluntario'),
        ),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            unique_together=set([('mesa', 'opcion')]),
        ),
        migrations.AlterUniqueTogether(
            name='votomesaoficial',
            unique_together=set([('mesa', 'opcion')]),
        ),
        migrations.AlterUniqueTogether(
            name='voluntario',
            unique_together=set([('tipo_dni', 'dni')]),
        ),
        migrations.AlterUniqueTogether(
            name='datodecontacto',
            unique_together=set([('tipo', 'valor', 'content_type', 'object_id')]),
        ),
    ]
