# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_auto_20170926_2307'),
        ('fiscales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votomesaoficial',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votomesareportado',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacionvoluntario',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='elecciones.Mesa'),
        ),
        migrations.AlterField(
            model_name='asignacionvoluntario',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='fiscales.Voluntario'),
        ),
        migrations.AlterUniqueTogether(
            name='votomesaoficial',
            unique_together=set([('mesa', 'opcion', 'categoria')]),
        ),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            unique_together=set([('mesa', 'opcion', 'categoria')]),
        ),
    ]
