# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def crear_categoria(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Categoria = apps.get_model('elecciones', 'Categoria')
    Opcion = apps.get_model('elecciones', 'Opcion')
    Eleccion = apps.get_model('elecciones', 'Eleccion')
    Mesa = apps.get_model('elecciones', 'Mesa')

    e, _ = Eleccion.objects.get_or_create(id=1, defaults={'nombre': 'Elecciones Generales 2017'})
    cat, _ = Categoria.objects.get_or_create(id=1,
        defaults={
            'nombre': 'Elecciones a Senador Nacional',
            'orden': 1,
            'cargo': 'Senadores Nacionales',
            'eleccion': e,
        }
    )
    cat.opciones.set(Opcion.objects.all())
    for m in Mesa.objects.all():
        m.categorias.set([cat])


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_auto_20170926_2307'),
        ('fiscales', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_categoria),
        migrations.AddField(
            model_name='votomesaoficial',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votomesareportado',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacionvoluntario',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='elecciones.Mesa'),
        ),
        migrations.AlterField(
            model_name='asignacionvoluntario',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='fiscales.Voluntario'),
        ),
        migrations.AlterUniqueTogether(
            name='votomesaoficial',
            unique_together=set([('mesa', 'opcion', 'categoria')]),
        ),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            unique_together=set([('mesa', 'opcion', 'categoria')]),
        ),
    ]
