# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcion',
            old_name='es_contable',
            new_name='es_partido',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='url_datos_oficiales',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='url_pdf_datos_oficiales',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='obligatorio',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='partido',
        ),
        migrations.AddField(
            model_name='mesa',
            name='circuito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Circuito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcion',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Partido',
        ),
    ]
