# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import elecciones.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elecciones', '0002_auto_20170905_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre descriptivo interno. Ej: Elecciones de Concejales de Tres de Febrero', max_length=100)),
                ('cargo', models.CharField(help_text='Nombre del cargo/s elegible. Ej. Senadores Nacionales', max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['cargo'])),
                ('orden', models.PositiveIntegerField(blank=True, help_text='Orden en la boleta', null=True)),
            ],
            options={
                'verbose_name': 'Categoría elegible',
                'verbose_name_plural': 'Categorías elegibles',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acta_oficial', 'Acta oficial'), ('acta_partidaria', 'Acta Partidaria'), ('telegrama_oficial', 'Telegrama oficial')], max_length=50)),
                ('archivo', models.ImageField(blank=True, null=True, upload_to=elecciones.models.path_documento)),
            ],
        ),
        migrations.RemoveField(
            model_name='eleccion',
            name='opciones',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='eleccion',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='foto_acta',
        ),
        migrations.AddField(
            model_name='opcion',
            name='obligatorio',
            field=models.BooleanField(default=True, help_text='Si se deshabilita, la carga de votos para esta opción no será obligatoria'),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['nombre']),
        ),
        migrations.AddField(
            model_name='documento',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Mesa'),
        ),
        migrations.AddField(
            model_name='documento',
            name='subido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='eleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Eleccion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='opciones',
            field=models.ManyToManyField(to='elecciones.Opcion'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='categorias',
            field=models.ManyToManyField(help_text='Qué se vota en esta mesa', to='elecciones.Categoria'),
        ),
    ]
