version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=escrutiniociudadano
      - POSTGRES_USER=escrutinio
      - POSTGRES_PASSWORD=development
  web:
    build: ./python-docker
    volumes:
      - ../:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
